language: go

go:
  - 1.10.x

notifications:
  email: false

sudo: required

services:
  - mysql
  - redis

install:
# init database
  - mysql -e 'CREATE DATABASE IF NOT EXISTS proxy_pool;'
  - cd ${GOPATH}/src/github.com/CX1ng/proxypool
  - mysql -e 'USE proxy_pool;SOURCE sql/ip_list.sql;'
# download software
  - go get -v github.com/Masterminds/glide
  - cd ${GOPATH}/src/github.com/Masterminds/glide && go install && cd -
# setting env
  - cd ${GOPATH}/src/github.com/CX1ng/proxypool
  - make deps

script:
  - make test
  - make build


