listen = ":7080"
storage = "redis"

[mysql]
dsn = "root:@tcp(127.0.0.1:3306)/?charset=utf8mb4,utf8&parseTime=True&loc=Local"
dbName =  "proxy_pool"
maxOpen = 1
maxIdle = 2

[redis]
dsn = "127.0.0.1:6379"
timeout = "3s"
protocol = "tcp"
db = 1

# 配置要爬取的代理网站
[[proxy_web]]
name = "kuaidaili" #现支持“kuaidaili”、“xici”
beginPageNum = 1   #开启爬取页数
endPageNum = 100     #最大页数, 0为不限制，
timeInterval = 30
[[proxy_web]]
name = "xici"
beginPageNum = 1 
endPageNum = 100
timeInterval = 30
